/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.0.1-2-g2db2bdabbd-20220408"
#endif /* AVUTIL_FFVERSION_H */
